PINValidation/Models/ErrorViewModel.cs
using System;

namespace PINValidation.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PINValidation/Models/PinFomViewModel.cs
using System;
using System.ComponentModel;

namespace PINValidation.Models
{
    public class PinFormViewModel
    {
        [DisplayName("PIN")]
        public string Pin { get; set; } = "";

        public string Message { get; set; } = "";
    }
}

PINValidation/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using PINValidation.Models;

namespace PINValidation.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PINValidation/Controllers/PinFormController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using PINValidation.Contracts.Validation;
using PINValidation.Models;

namespace PINValidation.Controllers
{
    public class PinFormController : Controller
    {
        private readonly IPinValidator _pinValidator;

        public PinFormController(IPinValidator pinValidator)
        {
            this._pinValidator = pinValidator;
        }

        public IActionResult PinForm()
        {
            return View(new PinFormViewModel());
        }

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult PinForm(PinFormViewModel pinFormViewModel)
        {
            if(ModelState.IsValid && this._pinValidator.IsValid(pinFormViewModel.Pin))
            {
                pinFormViewModel = new PinFormViewModel();
                pinFormViewModel.Message = "The PIN you entered is valid!";
            }
            else
            {
                pinFormViewModel.Message = "The PIN you entered is NOT valid";
            }
            return View(pinFormViewModel);
        }
    }
}

PINValidation/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to Personal Identification Number validation web site. Please use link below.</h1>
    <a asp-area="" asp-controller="PinForm" asp-action="PinForm">Go to PIN form</a>
</div>

PINValidation/Views/PinForm/PinForm.cshtml
@{
    ViewData["Title"] = "PIN form";
    string message = Model.Message;
}
@model PinFormViewModel
@if (message.Length > 0)
{
    <p>@message</p>
}
<form asp-action="PinForm" asp-controller="PinForm">
    <label asp-for="Pin"></label>
    <input asp-for="Pin" placeholder="Enter your pin" />
    <input type="submit" />
</form>

PINValidation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PINValidation</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PINValidation</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - PINValidation - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>